spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8338
    url: jdbc:mariadb://localhost:3306/bookmaru

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        format_sql: false

